import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "./Context/CartContext";

// إعداد الخطوط
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <CartProvider>
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
          <head>
            <link
              rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
              crossOrigin="anonymous"
              referrerPolicy="no-referrer"
            />
          </head>
          <body className="flex flex-col min-h-screen antialiased">
            <Header />

            {/* المحتوى الرئيسي ياخد المساحة المتاحة */}
            <main className="flex-grow">
              {children}
            </main>

            <Footer />
          </body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
